<MyButton@Button>:
    font_size: 32

<MyGrid>:
    id: calc
    display: entry
    rows: 6
    padding: 5
    spacing: 5
    
    BoxLayout:
        TextInput:
            id: entry
            font_size: 32
            multiline: False
    BoxLayout:
        spacing: 5
        MyButton:
            front_size: 32 
            text: "1"
            on_press: entry.text += self.text
        MyButton:
            front_size: 32 
            text: "2"
            on_press: entry.text += self.text
        MyButton:
            front_size: 32 
            text: "3"
            on_press: entry.text += self.text
        MyButton:
            front_size: 32 
            text: "+"
            on_press: entry.text += self.text
    BoxLayout:
        spacing: 5
        MyButton:
            front_size: 32 
            text: "4"
            on_press: entry.text += self.text
        MyButton:
            front_size: 32 
            text: "5"
            on_press: entry.text += self.text
        MyButton:
            front_size: 32 
            text: "6"
            on_press: entry.text += self.text
        MyButton:
            front_size: 32 
            text: "-"
            on_press: entry.text += self.text
    BoxLayout:
        spacing: 5
        MyButton:
            front_size: 32 
            text: "7"
            on_press: entry.text += self.text
        MyButton:
            front_size: 32 
            text: "8"
            on_press: entry.text += self.text
        MyButton:
            front_size: 32 
            text: "9"
            on_press: entry.text += self.text
        MyButton:
            front_size: 32 
            text: "*"
            on_press: entry.text += self.text
    BoxLayout:
        spacing: 5
        MyButton:
            front_size: 32 
            text: "Clear"
            on_press: entry.text = ""
        MyButton:
            front_size: 32 
            text: "0"
            on_press: entry.text += self.text
        MyButton:
            front_size: 32 
            text: "="
            on_press: calc.Compute(entry.text)
        MyButton:
            front_size: 32 
            text: "/"
            on_press: entry.text += self.text
    BoxLayout:
        spacing: 5
        MyButton:
            front_size: 32 
            text: "("
            on_press: entry.text += self.text
        MyButton:
            front_size: 32 
            text: ")"
            on_press: entry.text += self.text
        MyButton:
        #This works like modulo
            front_size: 32 
            text: "%"
            on_press: entry.text += self.text
        MyButton:
            front_size: 32 
            text: "."
            on_press: entry.text += self.text

